---
galaxy_info:
  role_name: web_server
  author: 4Linux DevOps
  description: Instalação e Configuração do servidor Apache
  company: 4Linux
  license: GPLv3
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - 20.04
    - name: CentOS
      versions:
        - 8
  galaxy_tags:
    - apache
dependencies: []
