---
- hosts: local
  tasks:
    - name: Adicionar estrutura de diret√≥rios atraves de variavel
      file: 
        dest: "{{ diretorios }}" 
        state: directory
        recurse: yes
        owner: root
        group: root 
        mode: 775
