---
- hosts: webservers
  tasks:
    - name: Instala Apache no Debian/Ubuntu
      when: ansible_os_family == "Debian" 
      apt: 
        name: apache2 
        state: present 
        update_cache: true
      register: apache2_installed
    - name: Instala Apache no CentOS
      when: ansible_os_family == "RedHat"
      yum:
        name: httpd 
        state: present
      register: httpd_installed

